### ISSUE TITLE
Version 1.4.2 doesn't load fixture

### ISSUE THREAD

**Issue by crawlik** [travisjeffery/jasmine-jquery-rails#1]
Hi, we run into an issue with latest 1.4.2 release. 

``` coffee
  it 'should load fixture', ->
    loadFixtures('menu.html')
    console.log(jasmine.getFixtures())
```

Above test produces the following result 

``` json
jsDump: {
  "containerId": "jasmine-fixtures",
  "fixturesCache_": {
    "menu.html": undefined
  },
  "fixturesPath": "spec/javascripts/fixtures"
}
```

1.3.1 loads the fixture just fine

``` json
jsDump: {
  "containerId": "jasmine-fixtures",
  "fixturesCache_": {
    "menu.html": "<div class='wizard-container'></div>"
  },
  "fixturesPath": "spec/javascripts/fixtures"
}
```

`menu.html` resides under `spec/javascripts/fixtures` with a simple content

`<div class='wizard-container'></div>`

Any idea what might be wrong?

**Comment by previousgtbash** [comment]
The current fixturesPath won't work with Rails Assets Pipeline. I changed them to `assets/fixtures` path. If you want use my fork.

https://github.com/danilotorrisi/jasmine-jquery-rails

**Comment by travisjeffery** [comment]
@danilotorrisi if you use the jasmine gem (as you should) then it does.

@crawlik there wasn't any change that should affect this, I made another small project/repo to test the current implementation and the fixture was found as expected. Maybe you made some other changes that are affecting this?

**Comment by previousgtbash** [comment]
@travisjeffery I use jasminerice right now so probably that's why I have this problem.

**Comment by crawlik** [comment]
I use jasminerice as well and wonder how does it affects loading path.

**Comment by travisjeffery** [comment]
Yeah the reason is because jasmine rice servers it's own jasmine-jquery.js. I'll make a pr and see if he'll stop use this instead.

**Comment by travisjeffery** [comment]
closing this, this is a problem with jasminerice
