### ISSUE TITLE
Fixtures not loading properly?

### ISSUE THREAD

**Issue by jondkinney** [travisjeffery/jasmine-jquery-rails#4]
I'm trying to get fixtures working, but having issues.

In my gemfile (in the development & test group):

``` ruby
gem 'jasmine-rails'
gem 'jasmine-jquery-rails'
```

I have the following folder structure:

My fixture: `/spec/javascripts/fixtures/order_form.html`

Jasmine Spec Helper: `/spec/javascripts/helpers/spec_helper.coffee`

in my spec_helper.coffee

``` coffeescript
#=require jquery
#=require jasmine-jquery
```

Things seem to be loading

![screen shot 2013-09-03 at 10 46 55 pm](https://f.cloud.github.com/assets/4521/1077946/b7825ef4-1514-11e3-9ca3-97fcdbf8195d.png)

But the test fails with a 404 fixture file now found.

![jasmine_fixture_failure](https://f.cloud.github.com/assets/4521/1077948/bcb0073c-1514-11e3-8012-52da84a5524c.png)

If I go into the error I am presented with the following error on the 404 itself:

``` html
<h1>Routing Error</h1>
<p><pre>No route matches [GET] &quot;/spec/javascripts/fixtures/order_form.html&quot;</pre></p>
<p>
  Try running <code>rake routes</code> for more information on available routes.
</p>
```

I've also tried adding this to my spec_helper.coffee (though I'm not sure why this would be required).

``` ruby
jasmine.getFixtures().fixturesPath = 'assets/fixtures'
```

And while it made the 404 go away, the spec doesn't pass like it should because I still don't think the fixture is being loaded properly. I say this because it's un-modified code from Railscasts that I know should pass. I'm just trying to test to make sure everything is wired up properly!

My `spec/javascripts/support/jasmine.yml` file is very minimal per the suggestion of https://github.com/searls/jasmine-rails#asset-pipeline-support

``` yaml
# minimalist jasmine.yml configuration when leveraging asset pipeline
spec_files:
  - "**/*[Ss]pec.{js,coffee}"
```

Any help would be greatly appreciated!

**Comment by jondkinney** [comment]
So I ended up just using [jasmine-fixtures](http://searls.testdouble.com/posts/2011-12-11-jasmine-fixtures.html) instead. However, this is still a problem that probably should be fixed. I'm happy to help so I'll leave this open.

**Comment by wndxlori** [comment]
I'm experiencing this problem now.  Any assistance would be appreciated.

**Comment by jondkinney** [comment]
@wndxlori I never found a solution unfortunately. I just switched to using jasmine-fixtures instead. Hopefully someone will come along that can get this sorted...

**Comment by ChristopherWerby** [comment]
Giving a bump to this problem because I'm having exactly the same issue.  Rails 3.2.11.  I'm using a more expansive jasmine.yml file than the original poster -- mine comes almost exactly from the jasmine documentation -- but I've tried the minimal version too with no luck.  Jasmine-fixtures doesn't seem to be a solution for me, because I'm trying to test json server returns.

I read the previous closed issue which involved jasmine-rice.  I'm not using jasmine-rice.  I'm using the gem 'jasmine-rails' followed by gem 'jasmine-jquery-rails', and gem 'sinon-rails'.  (gem 'jquery-rails' is above in my gemfile.)  I pulled the sinon rails gem as a test, but it didn't resolve the issue.

**Comment by wndxlori** [comment]
Christopher, you might also be interested in https://github.com/pivotal/jasmine-ajax

I almost started using that, but in the end, jasmine-fixtures did the job, although I really would have preferred to continue to use jasmine-jquery-rails fixtures.

**Comment by ChristopherWerby** [comment]
Thank you, Lori!

I'll check it out.

It's driving me crazy though that I can't figure out the issue.  I'm sure that it must be some configuration detail that I've missed.

## Best,

Christopher Werby
Pipsqueak Productions, LLC
http://www.Pipsqueak.com

**Comment by travisjeffery** [comment]
Hey y'all there was a bug in the pipeline that was fixed in v3.2.13. Upgrade Rails to v3.2.13 and it's fixed. There's no problem with this gem.

**Comment by jondkinney** [comment]
@travisjeffery I was running either Rails 3.2.13 or 3.2.14 when I filed this issue.

**Comment by travisjeffery** [comment]
find the exact rails version. same with ruby. 

clone this and see if it works for you: https://github.com/travisjeffery/jasmine-jquery-rails-issue-4

**Comment by lazylester** [comment]
I'm seeing the same problem... fixture not found. Using Rails4. Error message is:
ActionController::RoutingError (No route matches [GET] "/spec/javascripts/fixtures/home_fixture.html")

How does Rails know that this is not a route to be interpreted but a file to be loaded (like an asset?).

I tried the jasmine-jquery-rails-issue-4 app and it works, but I couldn't get it working under Rails4.

Under Rails4 the 'rake jasmine' task for jasmine-jquery-rails-issue-4 can't be found. I haven't figured out why.

**Comment by randoum** [comment]
I come with a temporary solution that works well for me. While waiting for a better solution

I am using a standard installation with
- rails 4.0.1
- jasmine-rails 0.5.0
- jasmine-jquery-rails 1.5.9

The idea is to mount the directory _spec/javascripts/fixtures_ through the **routes.rb** file to give jasmine access to fixture files through the _/spec/javascripts/fixtures_ URI

Create an initializer, ex **/initializers/jasmine_fixtures.rb**

``` ruby
# Map fixtures directory for Jasmine suite
if defined?(Jasmine::Jquery::Rails::Engine)
  JasmineFixtureServer = Proc.new do |env|
    Rack::Directory.new('spec/javascripts/fixtures').call(env)
  end
end
```

Part of **route.rb**

``` ruby
  # Mount Jasmine engine
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # mount spec/javascripts/fixtures directory
  mount JasmineFixtureServer => '/spec/javascripts/fixtures' if defined?(Jasmine::Jquery::Rails::Engine)
```

**Comment by lazylester** [comment]
yes that works, Randoum, thank you very much.

A tiny bit simpler still is to mount the JasmineFixtureServer at "spec/javascripts/fixtures", as this is the default fixture path. Then you don't have to include the "beforeEach" statement.

I can imagine that your approach could be included in the jasmine-jquery-rails engine as a permanent solution but I wasn't able to figure out how to do it.

**Comment by randoum** [comment]
Yes off course, assign the path at your convenience. I updated my previous comment to make it clearer for the next persons that would be looking for this solution. Can you please verify/confirm it's correct cause I did not test it like this.

I tried as well to mount the path from jasmine-jquery-rails engine, but I know nothing about Rails engines :) Let's wait for a skilled guy to pass-by

**Comment by lazylester** [comment]
Yes, Randoum, you have it correct. Thanks again.

**Comment by Trevoke** [comment]
So.. Is this how we should set up loading fixtures from now on?

**Comment by codener** [comment]
@randoum, thanks a lot! Your approach got me running.

Just want to note that I'm not using `jasmine-jquery-rails`, but `jasmine-jquery`. By changing `if defined?(Jasmine::Jquery::Rails::Engine)` to `if defined?(JasmineRails)`, I made it work for my stack.

**Comment by adamphillips** [comment]
We had the same problem. We also wanted to be able to import application styles for particular components into the fixture styles so that if they were changed in a way that broke the component, the tests would fail. We also wanted to be able to use the less css compiler in our fixture styles.

Building on @randoum's idea above, we set up a Sprockets environment and mounted that. The basic result uses the same changes to routes.rb but the initializer looks something like this

``` Ruby
# Setup Sprockets environment for serving Jasmine fixtures
JasmineFixtureServer = Sprockets::Environment.new

JasmineFixtureServer.append_path 'app/assets/stylesheets'
JasmineFixtureServer.append_path 'spec/javascripts/fixtures'

JasmineFixtureServer.logger = Rails.logger

# Copy over the less configuration from the application
JasmineFixtureServer.context_class.class_eval do
  class_attribute :less_config
  self.less_config = Rails.application.config.less
end
```

**Comment by Xiaohong-Deng** [comment]
@randoum Your workaround is still needed in Aug. 2017 for Rails 4.2.6. Thanks.
