### ISSUE TITLE
Upgrade to jasmine-jquery v2.0.0

### ISSUE THREAD

**Issue by christianvuerings** [travisjeffery/jasmine-jquery-rails#6]
Since jasmine-jquery has been upgraded to 2.0.0, it would be great if we can upgrade this gem.

See https://github.com/velesin/jasmine-jquery/commit/fb006ee1164178ac42a4daffcf94a793db5e42a8

**Comment by travisjeffery** [comment]
fixed by https://github.com/travisjeffery/jasmine-jquery-rails/commit/fdde0a00a2f7f9fc88f9038b0041c52c941a7da0 2.0.2
